Done tasks
js-tasks-ru/js-20220729_iromor pull request #5
Opened 2022-08-16 06:57 UTC by ichaplin85

В первом задании проходит половина тестов( Не разобрался как сделать проверку находящегося элемента без обращения к DOM.
Во втором задании сортировка и отображение работает, но ни один тест не проходит(

2022-08-16 06:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-16 14:12 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    console.log(elements);
не оставляйте отладочные консоли

2022-08-16 14:12 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  constructor(message = 'Hello World', { duration = 1000, type = 'success' } = {}) {
'Hello World' - этого не должно тут быть

2022-08-16 14:12 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(html = document.body) {
👍 good

2022-08-16 14:13 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const notification = document.querySelectorAll('.notification');
попробуйте заменить обращение к `DOM` на сохранение ссылки на предыдущий нотификейшен в статическом поле

2022-08-16 14:13 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  initEventListeners() {
не оставляйте пустые методы

2022-08-16 14:15 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          <span>Image</span>
этого `Image`, `Quantity` и т.д не должно быть в тимплейте. Ведь у нас вообще могут быть совершенно другие данные и соответственно колонки в  таблице (посмотрите на тесты)

2022-08-16 14:15 UTC, dosandk requested changes
посмотрите решения которые мы разберем сегодня на занятии, после внесите правки

2022-08-18 22:42 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.spec.js
> +    console.log(notificationMessage);
не оставляйте отладочные консоли

2022-08-18 22:43 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.spec.js
> +    console.log(columns);
этих изменений не должно быть в PR

2022-08-18 22:43 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
good 👍

2022-08-18 22:44 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    // console.log(result.body.innerHTML);
не оставляйте закомментированный код в PR

2022-08-18 23:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-18 23:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-18 23:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-19 08:06 UTC, dosandk approved these changes
посмотрите коменты, тесты я поправил

2022-08-19 08:06 UTC, merged